name: Daily Auto Update  # Workflow 的名称

on:
  schedule:
    - cron: '0 10 * * *'  # 定义触发时间：每天 UTC 时间 10:00

jobs:
  update:
    runs-on: ubuntu-latest  # 运行在最新的 Ubuntu 虚拟机上

    steps:
      - name: Checkout repository  # 步骤 1：检出你的代码
        uses: actions/checkout@v4

      - name: Set up Python (如果你的脚本是 Python 写的)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script  # 步骤 2：运行你的更新脚本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 用于提交更改的令牌
          # 你可以在这里添加其他需要的环境变量，例如 API 密钥
        run: |
          # 在这里执行你的脚本
          # 例如：
          # python your_update_script.py

      - name: Commit and push changes  # 步骤 3：提交并推送更改
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "your-email@example.com"  # 替换为你的邮箱
          git config --local user.name "Your GitHub Username"  # 替换为你的 GitHub 用户名
          git add .
          git commit -m "Daily auto update" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF} || echo "No changes to push"
